spring:
  application:
    name: sac_lishchuk
  datasource:
    url: jdbc:postgresql://localhost:5432/lab2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

sac:
  password-config:
    min-complex-length: 8
  role-create-permit-list:
    ADMIN: [ADMIN, MODERATOR, USER]
    MODERATOR: [MODERATOR, USER]
