spring:
  application:
    name: sac_lishchuk
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

sac:
  error-prefix: SCA_ERR_
  password-config:
    min-complex-length: 8
