name: github-actions-practice

on:
  push:
    branches: 
      - master

env: 
  HOME_PATH: /home
  APPLICATION_NAME: sac_lishchuk-${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run maven tests
        run: |
          echo "Running tests..."
          mvn test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: build application
        run: |
          echo "Building application..."
          mvn install -DskipTests
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy application
        run: |
          echo "Deploying application..."
          echo "Application Name: $APPLICATION_NAME"
          echo "Home Path: $HOME_PATH"
      