name: github-actions-practice

on:
  push:
    branches: 
      - master

env: 
  HOME_PATH: /home
  APPLICATION_NAME: custom-app-name-from-env-variable

jobs:
  writing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write something to the file
        run: echo "example of the" >> file.txt

      - name: Upload file.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: file-artifact
          path: file.txt

  checking:
    runs-on: ubuntu-latest
    needs: writing
    steps:
      - name: Download file.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: file-artifact

      - name: List files in the directory
        run: ls -la

      - name: Print content of the file
        run: cat file.txt
  reading_dir:
    runs-on: ubuntu-latest
    needs: writing
    steps:
      - name: Echo job info
        run: |
          cd $HOME_PATH
          echo "The job for ${{ env.APPLICATION_NAME }} was finished at $(uptime)"

